-- ============================================================
-- BitBingo Seed Data – 25 Challenges (positions 0-24)
-- Position 12 is the center tile: "X Marks the Spot"
-- ============================================================

INSERT INTO challenges (position, title, description) VALUES
  (0,  'Two Sum',
       'Given an array of integers and a target, return indices of the two numbers that add up to the target.'),
  (1,  'Reverse String',
       'Write a function that reverses a string in-place without using built-in reverse utilities.'),
  (2,  'FizzBuzz',
       'Print numbers 1–100. For multiples of 3 print "Fizz", for multiples of 5 print "Buzz", for both print "FizzBuzz".'),
  (3,  'Palindrome Check',
       'Determine whether a given string reads the same forwards and backwards, ignoring case and spaces.'),
  (4,  'Fibonacci Sequence',
       'Generate the first N numbers of the Fibonacci sequence using both iterative and recursive approaches.'),
  (5,  'Binary Search',
       'Implement binary search on a sorted array and return the index of the target element, or -1 if not found.'),
  (6,  'Bubble Sort',
       'Sort an array of integers using the bubble sort algorithm and explain its time complexity.'),
  (7,  'Stack Implementation',
       'Implement a Stack class with push, pop, peek, and isEmpty operations using an array as the underlying structure.'),
  (8,  'Queue Implementation',
       'Implement a Queue class with enqueue, dequeue, front, and isEmpty operations using a linked-list approach.'),
  (9,  'Anagram Check',
       'Given two strings, determine whether they are anagrams of each other (same characters, different order).'),
  (10, 'Linked List Reversal',
       'Reverse a singly linked list in-place and return the new head node.'),
  (11, 'Valid Parentheses',
       'Given a string containing only brackets "()", "[]", "{}", check if the bracket sequence is valid and balanced.'),
  (12, 'X Marks the Spot',
       'Implement a circle printing logic based on coordinate geometry. Given radius r, print all integer (x, y) pairs that satisfy x² + y² ≤ r², centered at the origin.'),
  (13, 'Matrix Rotation',
       'Rotate an N×N matrix 90 degrees clockwise in-place without using extra matrix space.'),
  (14, 'Hash Map from Scratch',
       'Build a simple hash map with set, get, and delete methods using an array of buckets and a hash function.'),
  (15, 'String Compression',
       'Implement basic string compression: "aaabbc" → "a3b2c1". Return the original string if compression does not shrink it.'),
  (16, 'Merge Sort',
       'Sort an array using the merge sort algorithm. Demonstrate the divide, conquer, and merge phases clearly.'),
  (17, 'Tree In-order Traversal',
       'Perform in-order traversal of a binary search tree and return the nodes in sorted ascending order.'),
  (18, 'Graph BFS',
       'Implement Breadth-First Search on an adjacency-list graph and return the traversal order from a given start node.'),
  (19, 'Graph DFS',
       'Implement Depth-First Search on an adjacency-list graph both iteratively (using a stack) and recursively.'),
  (20, 'Power of Two',
       'Determine whether a given integer is a power of two using bitwise operations (no loops or recursion).'),
  (21, 'Coin Change',
       'Given coin denominations and a target amount, find the minimum number of coins needed to make up that amount.'),
  (22, 'Longest Common Subsequence',
       'Find the length of the longest common subsequence between two strings using dynamic programming.'),
  (23, 'Regex: Count Vowels',
       'Use regular expressions to count the total number of vowels in a given paragraph of text.'),
  (24, 'Quick Sort',
       'Sort an array using the quick sort algorithm with a pivot strategy of your choice. Discuss average vs worst-case.')
ON CONFLICT (position) DO NOTHING;
