-- ============================================================
-- BitBingo Session-Scoped Refactor
-- ============================================================

-- Ensure session ids are UUIDs generated by default.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE sessions
  ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- Teams (participants) must belong to a single session.
-- Backfill orphan rows to the latest session so constraint can be enforced.
WITH latest_session AS (
  SELECT id FROM sessions ORDER BY created_at DESC LIMIT 1
)
UPDATE participants
SET session_id = (SELECT id FROM latest_session)
WHERE session_id IS NULL;

ALTER TABLE participants
  ALTER COLUMN session_id SET NOT NULL;

-- Challenges become global question bank (no board position here).
ALTER TABLE challenges
  DROP CONSTRAINT IF EXISTS challenges_position_key;

ALTER TABLE challenges
  DROP CONSTRAINT IF EXISTS challenges_position_check;

ALTER TABLE challenges
  DROP COLUMN IF EXISTS position;

-- Session board composition: 25 mapped challenge slots per session.
CREATE TABLE IF NOT EXISTS session_challenges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
  challenge_id INTEGER NOT NULL REFERENCES challenges (id) ON DELETE CASCADE,
  position INTEGER NOT NULL CHECK (position BETWEEN 0 AND 24),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (session_id, position),
  UNIQUE (session_id, challenge_id)
);

ALTER TABLE session_challenges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "session_challenges_select_public"
  ON session_challenges FOR SELECT
  USING (true);

CREATE POLICY "session_challenges_insert_authenticated"
  ON session_challenges FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "session_challenges_update_authenticated"
  ON session_challenges FOR UPDATE
  USING (auth.role() = 'authenticated');

CREATE POLICY "session_challenges_delete_authenticated"
  ON session_challenges FOR DELETE
  USING (auth.role() = 'authenticated');

-- Backfill existing sessions with existing challenge mapping using challenge id ordering.
INSERT INTO session_challenges (session_id, challenge_id, position)
SELECT
  s.id,
  c.id,
  ROW_NUMBER() OVER (PARTITION BY s.id ORDER BY c.id) - 1 AS position
FROM sessions s
CROSS JOIN challenges c
WHERE NOT EXISTS (
  SELECT 1
  FROM session_challenges sc
  WHERE sc.session_id = s.id
)
AND c.id IN (
  SELECT id
  FROM challenges
  ORDER BY id
  LIMIT 25
);

-- Completions uniqueness should be per-session.
ALTER TABLE completions
  DROP CONSTRAINT IF EXISTS completions_participant_id_challenge_id_key;

ALTER TABLE completions
  ADD CONSTRAINT completions_participant_id_challenge_id_session_id_key
  UNIQUE (participant_id, challenge_id, session_id);
